#!/usr/bin/env python3
"""Derive the vendor-baseline dialect from a third-party comparison export.

The export itself is NEVER committed (see .gitignore). This reads it from a local path and emits
two artefacts we DO version:

  reference/requirements-vendor-baseline.yml   their 97 metrics as EsgRequirements, so our
                                               observations can be projected back into their
                                               format for a row-for-row diff
  docs/BASELINE_DEFECTS.md                     the defect analysis, regenerated from the data so
                                               every number in it is reproducible rather than
                                               asserted

    python3 scripts/build-vendor-baseline.py "/path/to/export.tsv"
"""
import sys, csv, collections, re, pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
src = pathlib.Path(sys.argv[1] if len(sys.argv) > 1 else
                   "../Proof_Sample_Comparison to HRW.tsv")
if not src.exists():
    sys.exit(f"comparison export not found: {src}\nusage: build-vendor-baseline.py <export.tsv>")

rows = list(csv.reader(src.open(newline="", encoding="utf-8-sig"), delimiter="\t"))
# Row 0 is a stray sheet title ("Table 1"); row 1 is the real header.
data = [r for r in rows[2:] if any(c.strip() for c in r) and len(r) >= 9]

metrics = {}
for domain, question, url, answer, rationale, category, dimension, metric, abbrev in (r[:9] for r in data):
    m = metrics.setdefault(abbrev, {"metric": metric, "category": category, "dimension": dimension,
                                    "questions": collections.Counter(), "answers": collections.Counter(),
                                    "blank_rationale": 0, "n": 0})
    m["questions"][question] += 1
    m["answers"][answer] += 1
    m["blank_rationale"] += (not rationale.strip())
    m["n"] += 1

QUANT = re.compile(r"\b(what was|what were|how many|how much|total amount|percent|number of|"
                   r"proportion|metric tons|describe|please provide|list and description|in what ways)\b", re.I)

def kind(m):
    q = m["questions"].most_common(1)[0][0]
    return "quantitative-or-narrative" if QUANT.search(q) else "categorical"

# Where our framework-neutral datapoints answer one of their metrics. Deliberately PARTIAL:
# 13 datapoints do not cover 97 questionnaire items, and pretending otherwise would be the same
# overclaiming this realm exists to beat. Unmapped metrics simply do not appear in the diff.
ANSWERS = {
    "SCO_2_EMI":       "ghg_scope2_location",
    "GHG_EMM_AVO_OPS": "ghg_scope1",
    "PAS_CLI_ACT_IMP": "climate_transition_plan",
    "FUT_CLI_GOA_TAR": "ghg_reduction_target",
    "CAR_RED_INI":     "ghg_reduction_target",
    "PER_RED_ENE_CON": "energy_consumption_total",
    "MAN_MON_ELE_USA": "energy_consumption_total",
    "MAN_MON_WAT_USA": "water_withdrawal_total",
    "WAT_MAN_POL":     "water_withdrawal_total",
    "BOA_DIS_ESG":     "board_sustainability_oversight",
    "ESG_POL_MUL_OPT": "business_conduct_policy",
}

out = ["# GENERATED by scripts/build-vendor-baseline.py — do not hand-edit.",
       "#",
       "# A third-party questionnaire rendered as EsgRequirements so our observations can be",
       "# projected into its language and diffed row-for-row. These codes are JOIN KEYS, not a",
       "# standard, and the baseline's own answers are NOT ground truth — see",
       "# docs/BASELINE_DEFECTS.md for why.",
       "#",
       f"# Source rows: {len(data)} | metrics: {len(metrics)} | domains: {len({r[0] for r in data})}",
       ""]
for ab, m in sorted(metrics.items()):
    title = m["metric"].replace('"', "'")
    out += [f"- type: EsgRequirement",
            f"  data: {{ id: vendor-{ab.lower().replace('_','-')}, code: {ab}, verified: false,",
            f"           title: \"{title}\", dimension: {m['dimension']}, category: \"{m['category']}\",",
            f"           baselineKind: {kind(m)}, baselineRows: {m['n']}, baselineDistinctAnswers: {len(m['answers'])} }}",
            f"  relations: [{{ predicate: IN_FRAMEWORK, to: {{ type: EsgFramework, id: vendor-baseline }} }}]"]
(ROOT / "reference/requirements-vendor-baseline.yml").write_text("\n".join(out) + "\n")

# ── the defect analysis, regenerated so every figure is checkable ────────────────────────────
yes_only   = [a for a, m in metrics.items() if set(m["answers"]) <= {"Yes"}]
quant      = [a for a, m in metrics.items() if kind(m) == "quantitative-or-narrative"]
quant_yes  = [a for a in quant if set(metrics[a]["answers"]) <= {"Yes"}]
quant_rows = sum(metrics[a]["n"] for a in quant_yes)
blank      = sum(m["blank_rationale"] for m in metrics.values())
worst      = sorted(((metrics[a]["n"], a) for a in quant_yes), reverse=True)[:8]

md = f"""# What the baseline gets wrong

Regenerated by `scripts/build-vendor-baseline.py`. Every figure below is arithmetic over the
comparison export — re-run it and check.

| | |
|---|---|
| Rows | {len(data):,} |
| Metrics | {len(metrics)} |
| Domains assessed | {len({r[0] for r in data})} |

## 1. It cannot say no

**{len(yes_only)} of {len(metrics)} metrics have exactly one distinct answer across the entire corpus, and that
answer is "Yes".**

Absence is never recorded, so a company that publishes no ESG policy is indistinguishable from
one that was never assessed for it. As a score this is meaningless: every domain scores full
marks on everything it appears in. It is a confirmation machine, not an assessment.

## 2. It answers quantitative questions with "Yes"

**{len(quant_yes)} of the {len(quant)} metrics that ask for a number or a description are answered only "Yes" —
{quant_rows} rows.**

| Rows | Metric | The question actually asked |
|---|---|---|
""" + "\n".join(
    f"| {n} | `{a}` | {' '.join(metrics[a]['questions'].most_common(1)[0][0].split())[:110]} |"
    for n, a in worst) + f"""

"What were your organization's Scope 2 greenhouse gas emissions during the reporting period
(metric tons)?" is answered `Yes`. So is "Describe the past climate actions implemented by your
organization" — {metrics['PAS_CLI_ACT_IMP']['n']} times.

The root cause is visible in the question text: these are **self-report survey questions**,
written to be sent to a company, then repurposed as prompts for scraping a website. Nothing in
the pipeline holds an answer to the form its own question demands.

## 3. Its citations do not support its claims

{blank:,} of {len(data):,} rows ({blank/len(data)*100:.1f}%) carry no rationale at all. Among those that do, the
cited pages include `/cookie-policy`, `/terms-and-conditions/`, `/calendario/` and
`/1900x600_schrumpftunnel/` — pages with no bearing on sustainability.

## 4. Its firmographics are inferred from the domain name

Country of legal registration is a registry fact. Of the 244 rows asserting one, 128 sit on a
country ccTLD — and 116 of those (91%) were assigned exactly the country the TLD implies. Only
12 of 877 firmographic rows cite an imprint or legal page, the one page type obliged to carry a
registered office. Where the pipeline was not simply reading the TLD it broke:
`moog.co.uk -> Sweden`, `csl.com.au -> Denmark`, `broadcastaustralia.com.au -> Luxembourg`.

A company registered in Bermuda has no reason to say so on its website. This class of question
should never have been asked of a website at all — which is why `sourceClass` exists in our
catalogue and nothing of class `registry` is scraped.

## How this realm answers each

| Defect | Answer |
|---|---|
| Cannot say no | `not_disclosed` is a first-class value the extractor is instructed to prefer |
| "Yes" to a number | `answerType: quantity` — a number, a unit and a period, or nothing |
| Unsupported citations | every observation carries a verbatim quote and the chunk id it came from, so a citation can be **checked** |
| Inferred firmographics | `sourceClass: registry` datapoints are never read from a website |
"""
(ROOT / "docs/BASELINE_DEFECTS.md").write_text(md)

print(f"reference/requirements-vendor-baseline.yml — {len(metrics)} requirements")
print(f"docs/BASELINE_DEFECTS.md — {len(md.splitlines())} lines")
print(f"mapped to our datapoints: {len(ANSWERS)}/{len(metrics)} (deliberately partial)")
